### ISSUE TITLE
https/wss 配置，最新演示环境无法发送消息

### ISSUE THREAD

**Issue by zhangchanglong** [cskefu/cskefu#868]
## 现在行为
0712上午 在演示环境 https://demo.cskefu.com/ 测试，发现 无法发送消息

F12控制台提示：
socket.io.js:4163 WebSocket connection to 'wss://demo.cskefu.com:8036/socket.io/?userid=161e47d09233a9e4757b3beaa30a6ba8&session=359B486277B832F88E6DF1C7634DFD07&appid=104eac&osname=&browser=&skill=2c9e80867d65eb5c017d65f17ceb0019&nickname=Guest_%401ks1co&title=%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%20%7C%20%E5%BC%80%E6%BA%90%E5%AE%A2%E6%9C%8D%E7%B3%BB%E7%BB%9F_%E6%99%BA%E8%83%BD%E5%AE%A2%E6%9C%8D_%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%AE%A2%E6%9C%8D&url=https%3A%2F%2Fdemo.cskefu.com%2Ftestclient.html&traceid=a6419758ade04c019e9f27ada49ef26f&EIO=3&transport=websocket' 
failed: WebSocket is closed before the connection is established.

## 预期行为
能正常发送消息

## 操作系统

- [ ] Windows

**Comment by hailiang-wang** [comment]
WSS 链接默认是使用 443 端口，其设置识别是否有环境变量：

`CS_IM_SERVER_SSL_PORT`

 docker compose 配置

https://github.com/cskefu/cskefu/blob/da8f78e2d98425f02c49f62853e6e5085bf00a88/docker-compose.yml#L21

**Comment by lecjy** [comment]
是在docker环境下才出现这个问题吗？

**Comment by hailiang-wang** [comment]
docker 方式部署，但是该问题应该发生在使用反向代理配置 https/wss 的情况下。

docker 方式启动，docker compose 如下

```
  contact-center:
    image: ${CC_IMAGE:-cskefu/contact-center:develop}
    restart: always
    ports:
      - "${CC_WEB_PORT:-8035}:8035"
      - "${CC_SOCKET_PORT:-8036}:8036"
    volumes:
      - ./contact-center/data:/data
      - ./contact-center/logs:/logs
    environment:
      - "JAVA_OPTS=-Xmx${CC_JAVA_XMX:-12288m} -Xms${CC_JAVA_XMS:-2048m} -XX:PermSize=256m -XX:MaxPermSize=1024m -Djava.net.preferIPv4Stack=true --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true --illegal-access=warn"
      - SERVER_PORT=8035
      - SERVER_LOG_PATH=/logs
      - SERVER_LOG_LEVEL=${LOG_LEVEL:-WARN}
      - WEB_UPLOAD_PATH=/data
      - UK_IM_SERVER_PORT=8036
      - UK_IM_SERVER_HOST=localhost
      - UK_IM_SERVER_THREADS=10
      # 春松客服配置 HTTPs / HTTPs for CSKeFu
      # In detail
      #     1) https://chatopera.blog.csdn.net/article/details/105820829
      #     2) https://github.com/cskefu/cskefu/issues/414#issuecomment-1437767407
      # In short
      #     1) Setup Load Balancing / Reverse Proxy
      #     2) Modify CS_IM_SERVER_SSL_PORT
      #         2.1 comment out CS_IM_SERVER_SSL_PORT envronment variable to redirect HTTPs requests to 443 port
      #         2.2 Or just remove below line .
      - CS_IM_SERVER_SSL_PORT=443
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWD:-123456}
```
